baseURL = 'http://eddiewelker.com/'
languageCode = 'en-us'
title = 'eddiewelker.com'
theme = 'ananke'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[pagination]
pagerSize = 10

[params]
recent_posts_number = 8

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/edwelker"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/edwelker"
[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/edwelker"
