# ananke seems to be the standard theme, but it frustrates me
# https://github.com/Lednerb/bilberry-hugo-theme seems good for photos, but is a little showy
# https://github.com/Vimux/Mainroad is what I'll probably go with for now.
# https://github.com/lon9/hugo_stars for browsing

baseURL = 'http://eddiewelker.com/'
languageCode = 'en-us'
title = 'eddiewelker.com'
theme = 'ananke'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']
SummaryLength = 100
sectionPagesMenu = 'main'

[menus]
 [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
 [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 20

[permalinks]
  [permalinks.page]
    posts = '/articles/:year/:month/:day/:slug/'
  [permalinks.section]
    posts = '/articles/'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[pagination]
pagerSize = 20

[params]
author = "Eddie Welker"
recent_posts_number = 8
featured_image = "/header/springs.jpg"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
cover_dimming_class = "bg-black-40"


# https://github.com/theNewDynamic/gohugo-theme-ananke/blob/main/exampleSite/config.toml

# [params.ananke.social.share]
# networks = [
#   "instagram",
#   "spotify",
#   "github"
# ]

[params.ananke.social.follow]
networks = [
  "instagram",
  "spotify",
  "github"
]

[params.ananke.social.instagram]
username = "edwelker"

[params.ananke.social.github]
username = "edwelker"

[params.ananke.social.spotify]
username = "edwelker"

[params.ananke.social.networks.spotify]
slug = "spotify"
label = "spotify"
profile = "https://open.spotify.com/user/%s"
# https://github.com/FortAwesome/Font-Awesome/tree/6.x/svgs/brands
icon = "spotify"

[services]
  [services.googleAnalytics]
    id = ''
  [services.rss]
    limit = -1
