baseURL = 'http://eddiewelker.com/'
languageCode = 'en-us'
title = 'eddiewelker.com'
theme = 'ananke'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

[menu]
 [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[pagination]
pagerSize = 10

[params]
recent_posts_number = 8
github = "https://github.com/edwelker"
featured_image = "/images/learningjQuery.jpg"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"


# https://github.com/theNewDynamic/gohugo-theme-ananke/blob/main/exampleSite/config.toml

[params.ananke.social.share]
networks = [
  "instagram",
  "spotify",
  "github"
]

[params.ananke.social.follow]
networks = [
  "instagram",
  "spotify",
  "github"
]

[params.ananke.social.instagram]
username = "edwelker"

[params.ananke.social.github]
username = "edwelker"

[params.ananke.social.spotify]
username = "edwelker"

[params.ananke.social.networks.spotify]
slug = "spotify"
label = "spotify"
profile = "https://open.spotify.com/user/%s"
# https://github.com/FortAwesome/Font-Awesome/tree/6.x/svgs/brands
icon = "spotify"
