# ananke seems to be the standard theme, but it frustrates me
# https://github.com/Lednerb/bilberry-hugo-theme seems good for photos, but is a little showy
# https://github.com/Vimux/Mainroad is what I'll probably go with for now.
# https://github.com/lon9/hugo_stars for browsing

baseURL = 'http://eddiewelker.com/'
languageCode = 'en-us'
title = 'eddiewelker.com'
theme = 'bilberry-hugo-theme'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']
SummaryLength = 100
sectionPagesMenu = 'main'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 30

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[pagination]
pagerSize = 20

[params]
author = "Eddie Welker"
paginate = 10
resizeImages = false
gravatarEMail = "eddie.welker@gmail.com"
permanentTopNav = true
enableMomentJs = true
showReadingTime = true
enableLightDarkTheme = true

# define your links with FontAwesome 5 (only free icons are supported)
# all icons https://fontawesome.com/icons?d=gallery&m=free
# brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
socialMediaLinks = [
  { link = "https://instagram.com/edwelker", icon = "fab fa-instagram" },
  { link = "https://www.flickr.com/photos/ed_welker/", icon = "fab fa-flickr" },
  { link = "https://github.com/edwelker", icon = "fab fa-github" },
  { link = "https://open.spotify.com/user/edwelker", icon = "fab fa-spotify" },
]

# show an archive link in the footer
showArchive = true

# archive grouping: "2006" by year, "2006-01" by month
archiveDateGrouping = "2006-01"

# credits line configuration
copyrightBy = "by eddie welker"
copyrightUseCurrentYear = true
copyrightYearOverride = "2005"
copyrightUrl = "https://github.com/edwelker"
creditsText = "eddiewelker.com"

[services]
    [services.googleAnalytics]
        ID = 'G-19CWWGK0FL'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# hugo setting, cross-theme
[permalinks]
  categories = "/:section/:slug/"
  [permalinks.page]
    posts = '/articles/:year/:month/:day/:slug/'
  [permalinks.section]
    posts = '/articles/'
