# ananke seems to be the standard theme, but it frustrates me
# https://github.com/Lednerb/bilberry-hugo-theme seems good for photos, but is a little showy
# https://github.com/Vimux/Mainroad is what I'll probably go with for now.
# https://github.com/lon9/hugo_stars for browsing

baseURL = 'http://eddiewelker.com/'
languageCode = 'en-us'
title = 'eddiewelker.com'
theme = 'bilberry-hugo-theme/v4'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']
SummaryLength = 400
sectionPagesMenu = 'main'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
author = "Eddie Welker"
paginate = 5
resizeImages = false
gravatarEMail = "eddie.welker@gmail.com"
permanentTopNav = true
enableMomentJs = true
showReadingTime = true
enableLightDarkTheme = false
amountLatestPostsInFooter = 5
amountCategoriesInFooter = 5
showFooterLanguageChooser = false

css_modules = ['custom.css']

# define your links with FontAwesome 5 (only free icons are supported)
# all icons https://fontawesome.com/icons?d=gallery&m=free
# brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
socialMediaLinks = [
  { link = "https://instagram.com/edwelker", icon = "fab fa-instagram" },
  { link = "https://www.flickr.com/photos/ed_welker/", icon = "fab fa-flickr" },
  { link = "https://github.com/edwelker", icon = "fab fa-github" },
  { link = "https://open.spotify.com/user/edwelker", icon = "fab fa-spotify" },
  { link = "https://www.strava.com/athletes/43444098", icon = "fab fa-strava" },
  { link = "https://trakt.tv/users/edwelker", icon = "fa-solid fa-film" },
  { link = "https://www.last.fm/user/edwelker", icon = "fab fa-lastfm" },
]

# show an archive link in the footer
showArchive = true
# archive grouping: "2006" by year, "2006-01" by month
archiveDateGrouping = "2006"

# TODO
# Enable an optional pinned page to display at the top of the index
pinnedPost = "/article/series-list/"
# Set to true to pin only to the first page, false to all pages
pinOnlyToFirstPage = true

# credits line configuration
copyrightBy = "by eddie welker"
copyrightUseCurrentYear = false
copyrightYearOverride = "2007"
copyrightUrl = "https://github.com/edwelker"
creditsText = "eddiewelker.com"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Change to 'true' if you need to render raw HTMLs whithin your markdown content
      unsafe = false
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

[services]
    [services.googleAnalytics]
        ID = 'G-19CWWGK0FL'

[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

# hugo setting, cross-theme
[permalinks]
  categories = "/:section/:slug/"
  [permalinks.page]
    posts = '/:year/:month/:day/:slug/'

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
